Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -55,16 +55,19 @@ jobs:
     needs: docker-build-push
     if: github.ref == 'refs/heads/main'
     steps:
-    - name: Start SSH agent
-      run: eval $(ssh-agent -s)
-    
-    - name: Add SSH private key
-      run: |
-        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
-    
-    - name: Check SSH agent status
-      run: ssh-add -l || echo "No identities found."
+     - name: Start SSH agent
+       run: |
+        eval $(ssh-agent -s)
+        ssh-add -l || echo "No identities found."  # Check if agent is running
 
-    - name: Deploy to Production Server
-      run: |
+     - name: Add SSH private key
+       run: |
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - || echo "Failed to add SSH key."
+
+     - name: Verify SSH agent status
+       run: |
+        ssh-add -l || echo "No identities found."
+
+     - name: Deploy to Production Server
+       run: |
           ssh -o StrictHostKeyChecking=no TakudzwaNhema@20.84.103.115 -p 822 "docker pull takue05/web-app-docker:latest && docker-compose up -d"
